import type {Metadata} from "next";
import "./globals.scss";
import {inter} from '@/shared/fonts/fonts'
import Navbar from "@/widgets/Navbar/Navbar";
import {NextIntlClientProvider, useMessages} from "next-intl";
import * as console from "console";
import StoreProvider from "@/shared/StoreProvider";
import SignUpForm from "@/features/SignUpForm/SignUpForm";
import Modal from "@/widgets/Modal/Modal";
import React from "react";
import Test from "@/widgets/Test/Test";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                       params: {locale}
                                   }: Readonly<{
    children: React.ReactNode;
    params: { locale: string }
}>) {
    const messages = useMessages();

    return (
        <html lang={locale}>
        <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
            <StoreProvider>
                <Navbar/>
                <Modal>
                    <SignUpForm/>
                </Modal>
            </StoreProvider>
            {children}
        </NextIntlClientProvider>

        </body>
        </html>
    );
}
