import type {Metadata} from "next";
import "./globals.scss";
import {inter} from '@/shared/fonts/fonts'
import {NextIntlClientProvider, useMessages} from "next-intl";
import StoreProvider from "@/shared/store/StoreProvider";
import React from "react";
import AuthModal from "@/widgets/AuthModal/AuthModal";
import {Navbar} from "@/widgets/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                       params: {locale}
                                   }: Readonly<{
    children: React.ReactNode;
    params: { locale: string }
}>) {
    const messages = useMessages();

    return (
        <html lang={locale}>
        <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
        </NextIntlClientProvider>

        </body>
        </html>
    );
}
